import type {
  AdminHotelCardDraftItem,
  AdminHotelRoomDraftItem,
} from "@/lib/admin-studio/card-collections"

type DefaultRoomSeed = Omit<AdminHotelRoomDraftItem, "id" | "sortOrder">

const DEFAULT_ROOM_SEEDS: DefaultRoomSeed[] = [
  {
    visible: true,
    name: "Quarto Duplo",
    category: "",
    occupancy: 2,
    beds: "1 cama de casal",
    amenities: [
      "Ar-condicionado",
      "Banheiro privativo",
      "TV de tela plana",
      "Wi-Fi gratuito",
      "Chuveiro",
      "Toalhas",
      "Roupa de cama",
      "Papel higiênico",
    ],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Duplo Standard",
    category: "",
    occupancy: 2,
    beds: "1 cama de casal",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Triplo",
    category: "",
    occupancy: 3,
    beds: "1 cama de solteiro + 1 cama de casal",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo",
    category: "",
    occupancy: 4,
    beds: "1 cama de casal + 1 beliche",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo Standard",
    category: "",
    occupancy: 4,
    beds: "1 cama de solteiro + 1 cama de casal",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo Clássico",
    category: "",
    occupancy: 4,
    beds: "2 camas de solteiro + 1 cama de casal",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo Comfort",
    category: "",
    occupancy: 4,
    beds: "1 cama de casal + 1 beliche",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo Deluxe",
    category: "",
    occupancy: 4,
    beds: "1 cama de casal + 1 beliche",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Quádruplo Econômico",
    category: "",
    occupancy: 4,
    beds: "1 cama de casal + 1 beliche",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Suíte Família",
    category: "",
    occupancy: 5,
    beds: "1 cama de solteiro + 1 cama de casal + 1 beliche",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
  {
    visible: true,
    name: "Quarto Família",
    category: "",
    occupancy: 6,
    beds: "1 cama de casal + 2 beliches",
    amenities: ["Wi-Fi gratuito"],
    breakfastIncluded: true,
    price: 322,
    taxesInfo: "Impostos e taxas incluídos",
    cancellation: "Cancelamento grátis antes da data limite",
    payment: "Não requer pré-pagamento – pague na acomodação",
    maxRooms: 5,
    ctaLabel: "Reservar",
    ctaTarget: "whatsapp",
  },
]

function normalizeMatchValue(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
}

export function getDefaultHotelRoomsTemplate(roomIdPrefix = "hotel-room"): AdminHotelRoomDraftItem[] {
  return DEFAULT_ROOM_SEEDS.map((room, index) => ({
    ...room,
    id: `${roomIdPrefix}-room-${index + 1}`,
    sortOrder: index,
  }))
}

export function isMarajoHotelCardLike(
  hotel: Pick<AdminHotelCardDraftItem, "id" | "linkedSlug" | "locales">,
) {
  const candidates = [
    hotel.id,
    hotel.linkedSlug,
    ...Object.values(hotel.locales).map((locale) => locale.title),
  ]

  return candidates.some((value) => normalizeMatchValue(value).includes("marajo")) || hotel.id === "hotel-partner-1"
}
