export const siteContent = {
  pt: {
    langLabel: "Idioma",
    heroTitle1: "Descubra o Paraíso",
    heroTitle2: "da Ilha de Marajó",
    heroSubtitle: "Aonde quer que você vá, nós te levamos. Encontre as melhores ofertas para sua próxima aventura.",
    heroButton: "Buscar",
    tabs: ["Voos", "Hotéis", "Pacotes", "Atividades", "Ônibus", "Carros"],
    stats: ["Hotéis", "Destinos", "Viajantes", "Avaliação"],
    premiumBadge: "Experiência premium em Soure",
    premiumTitle1: "Praia do",
    premiumTitle2: "Pesqueiro",
    premiumText: "Um dos cenários mais desejados do Marajó. Areia ampla, mar, cultura local e a experiência única de ver búfalos integrados à paisagem fazem do Pesqueiro um destino de alto apelo visual e emocional.",
    premiumHighlights: ["Praia icônica de Soure", "Experiência com búfalos", "Barracas à beira-mar", "Pôr do sol inesquecível"],
    premiumCta1: "Reservar experiência",
    premiumCta2: "Ver pacotes premium",
    premiumFooter1: "Galeria premium • Soure • Ilha de Marajó",
    premiumFooter2: "Auto play ativo • use as setas"
  },
  en: {
    langLabel: "Language",
    heroTitle1: "Discover the Paradise",
    heroTitle2: "of Marajó Island",
    heroSubtitle: "Wherever you want to go, we take you there. Find the best offers for your next adventure.",
    heroButton: "Search",
    tabs: ["Flights", "Hotels", "Packages", "Activities", "Bus", "Cars"],
    stats: ["Hotels", "Destinations", "Travelers", "Rating"],
    premiumBadge: "Premium experience in Soure",
    premiumTitle1: "Pesqueiro",
    premiumTitle2: "Beach",
    premiumText: "One of the most desired landscapes in Marajó. Wide sands, sea, local culture and the unique experience of seeing buffalo integrated into the scenery make Pesqueiro a destination with strong visual and emotional appeal.",
    premiumHighlights: ["Iconic beach in Soure", "Buffalo experience", "Beachfront spots", "Unforgettable sunset"],
    premiumCta1: "Book experience",
    premiumCta2: "See premium packages",
    premiumFooter1: "Premium gallery • Soure • Marajó Island",
    premiumFooter2: "Auto play active • use arrows"
  },
  fr: {
    langLabel: "Langue",
    heroTitle1: "Découvrez le Paradis",
    heroTitle2: "de l’île de Marajó",
    heroSubtitle: "Où que vous alliez, nous vous y emmenons. Trouvez les meilleures offres pour votre prochaine aventure.",
    heroButton: "Rechercher",
    tabs: ["Vols", "Hôtels", "Forfaits", "Activités", "Bus", "Voitures"],
    stats: ["Hôtels", "Destinations", "Voyageurs", "Note"],
    premiumBadge: "Expérience premium à Soure",
    premiumTitle1: "Plage de",
    premiumTitle2: "Pesqueiro",
    premiumText: "L’un des paysages les plus désirés de Marajó. Sable vaste, mer, culture locale et l’expérience unique de voir des buffles intégrés au décor font de Pesqueiro une destination à fort impact visuel et émotionnel.",
    premiumHighlights: ["Plage emblématique de Soure", "Expérience avec les buffles", "Espaces en bord de mer", "Coucher de soleil inoubliable"],
    premiumCta1: "Réserver l’expérience",
    premiumCta2: "Voir les forfaits premium",
    premiumFooter1: "Galerie premium • Soure • Île de Marajó",
    premiumFooter2: "Lecture automatique • utilisez les flèches"
  },
  es: {
    langLabel: "Idioma",
    heroTitle1: "Descubre el Paraíso",
    heroTitle2: "de la Isla de Marajó",
    heroSubtitle: "A donde quieras ir, nosotros te llevamos. Encuentra las mejores ofertas para tu próxima aventura.",
    heroButton: "Buscar",
    tabs: ["Vuelos", "Hoteles", "Paquetes", "Actividades", "Bus", "Autos"],
    stats: ["Hoteles", "Destinos", "Viajeros", "Calificación"],
    premiumBadge: "Experiencia premium en Soure",
    premiumTitle1: "Playa de",
    premiumTitle2: "Pesqueiro",
    premiumText: "Uno de los paisajes más deseados de Marajó. Arena amplia, mar, cultura local y la experiencia única de ver búfalos integrados al entorno hacen de Pesqueiro un destino de gran impacto visual y emocional.",
    premiumHighlights: ["Playa icónica de Soure", "Experiencia con búfalos", "Espacios frente al mar", "Atardecer inolvidable"],
    premiumCta1: "Reservar experiencia",
    premiumCta2: "Ver paquetes premium",
    premiumFooter1: "Galería premium • Soure • Isla de Marajó",
    premiumFooter2: "Reproducción automática • usa las flechas"
  }
} as const
