export const siteContent = {
  pt: {
    langLabel: "Idioma",
    heroTitle1: "Descubra o ParaÃ­so",
    heroTitle2: "da Ilha de MarajÃ³",
    heroSubtitle: "Aonde quer que vocÃª vÃ¡, nÃ³s te levamos. Encontre as melhores ofertas para sua prÃ³xima aventura.",
    heroButton: "Buscar",
    tabs: ["Voos", "HotÃ©is", "Pacotes", "Atividades", "Ã”nibus", "Carros"],
    stats: ["HotÃ©is", "Destinos", "Viajantes", "AvaliaÃ§Ã£o"],
    heroImageAlt: "Praia tropical de MarajÃ³",
    heroFieldOrigin: "Origem",
    heroFieldDestination: "Destino",
    heroFieldDates: "Datas",
    heroFieldPassengers: "Passageiros",

    home: {
      heroKicker: "Plataforma de destino â€¢ Ilha de MarajÃ³",
      heroSearchAria: "Busca por categoria",
      homeHeroImageAlt: "Paisagem da Ilha de MarajÃ³ com praia e cÃ©u amplo",
      destinationsEyebrow: "ExploraÃ§Ã£o",
      featureEyebrow: "ConfianÃ§a",
      featureLocationLabel: "Local",
      featureDurationLabel: "DuraÃ§Ã£o",
      featureInvestmentLabel: "Investimento",
      featureGalleryAlt: "Galeria MarajÃ³",
      newsletterEyebrow: "Newsletter premium",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Seu email",
      newsletterEmailPlaceholder: "Seu melhor email",
      newsletterImageAlt: "Viajante preparando a prÃ³xima viagem",
      offersEyebrow: "Reserva",
      offersConditions: "Ver condiÃ§Ãµes",
      partnersEyebrow: "Ecossistema",
      partnersBadge: "Parceiro",
      routesEyebrow: "ComparaÃ§Ã£o",
      routesViewPackage: "Ver pacote",
      socialEyebrow: "Prova social",
      socialRatingLabel: "AvaliaÃ§Ã£o",
      socialQuoteOpen: "â€œ",
      socialQuoteClose: "â€",
      topExperiencesEyebrow: "ExploraÃ§Ã£o",
      topExperiencesDetailsLabel: "Ver detalhes",
      travelGuideEyebrow: "Planejamento",
      travelGuideReadTimeSuffix: "de leitura",
      travelGuideReadCta: "Ler guia",
      whyEyebrow: "ImaginaÃ§Ã£o",
    },

    pages: {
      experiences: {
        eyebrow: "ExperiÃªncias",
        title: "ExperiÃªncias curadas para viver o MarajÃ³",
        subtitle: "SeleÃ§Ã£o premium com suporte local e reserva segura. Compare perfis e encontre a experiÃªncia certa para o seu momento.",
        detailsCta: "Ver detalhes",
      },
      experienceDetail: {
        eyebrow: "Detalhes",
        title: "O que torna essa experiÃªncia Ãºnica",
        includedTitle: "O que estÃ¡ incluÃ­do",
        priceLabel: "Investimento a partir de",
        perPersonLabel: "Por pessoa â€¢ avaliaÃ§Ã£o",
        reserveNow: "Reservar agora",
        planWithConcierge: "Planejar com concierge",
        reserveExperience: "Reservar experiÃªncia",
        talkToConsultant: "Falar com consultor",
      },
      packages: {
        eyebrow: "Pacotes",
        title: "Roteiros prontos para diferentes perfis de viagem",
        subtitle: "Combine experiÃªncias, hospedagens e suporte local com roteiros inteligentes e flexÃ­veis.",
        priceFrom: "A partir de",
        includes: "Inclui",
        itinerary: "ItinerÃ¡rio base",
        reserveCta: "Reservar pacote",
        consultCta: "Falar com consultor",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Planejamento personalizado para sua viagem",
        subtitle: "Conte com nosso time local para montar o roteiro ideal, com suporte real antes, durante e depois da reserva.",
        deliverTitle: "O que vamos entregar",
        deliverItems: [
          "Curadoria de experiÃªncias alinhadas ao seu perfil",
          "SugestÃ£o de roteiros, hospedagens e logÃ­stica",
          "NegociaÃ§Ã£o direta com parceiros locais",
        ],
        responseTitle: "Tempo de resposta",
        responseText: "AtÃ© 24 horas com atendimento humano.",
        nextStepLabel: "PrÃ³ximo passo",
        nextStepTitle: "Fale com nosso concierge e receba um plano sob medida.",
        whatsappCta: "Continuar no WhatsApp",
        whatsappFallback: "Configure `NEXT_PUBLIC_WHATSAPP_NUMBER` para habilitar o contato.",
        whatsappMessage: "OlÃ¡! Quero planejar uma viagem premium para o MarajÃ³. Gostaria de ajuda com experiÃªncias e pacotes.",
      },
    },

    premiumBadge: "ExperiÃªncia premium em Soure",
    premiumTitle1: "Praia do",
    premiumTitle2: "Pesqueiro",
    premiumText: "Um dos cenÃ¡rios mais desejados do MarajÃ³. Areia ampla, mar, cultura local e a experiÃªncia Ãºnica de ver bÃºfalos integrados Ã  paisagem fazem do Pesqueiro um destino de alto apelo visual e emocional.",
    premiumHighlights: ["Praia icÃ´nica de Soure", "ExperiÃªncia com bÃºfalos", "Barracas Ã  beira-mar", "PÃ´r do sol inesquecÃ­vel"],
    premiumCta1: "Reservar experiÃªncia",
    premiumCta2: "Ver pacotes premium",
    premiumFooter1: "Galeria premium â€¢ Soure â€¢ Ilha de MarajÃ³",
    premiumFooter2: "Auto play ativo â€¢ use as setas",

    packagesBadge: "Pacotes em destaque",
    packagesTitle: "Pacotes de Viagem",
    packagesSubtitle: "ExperiÃªncias selecionadas para viajantes que desejam viver o melhor da Ilha de MarajÃ³.",
    offerBadge: "Oferta premium",
    offerDescription: "Uma das experiÃªncias mais emblemÃ¡ticas de Soure, com paisagem marajoara, forte apelo fotogrÃ¡fico e conexÃ£o autÃªntica com a cultura local.",
    investmentLabel: "Investimento",
    detailsButton: "Ver detalhes",
    bookNow: "Reservar agora",

    experienceBadge: "ExperiÃªncia premium",
    experienceSectionTitle: "Uma experiÃªncia de alto valor visual e emocional",
    experienceGalleryTitle: "Galeria",
    includedLabel: "IncluÃ­do",
    continueBooking: "Continuar para reserva",
    backToPackages: "Ver pacotes",

    checkoutBadge: "Finalizar reserva",
    fullName: "Nome completo",
    email: "Email",
    phone: "Telefone / WhatsApp",
    experienceDate: "Data da experiÃªncia",
    travelers: "NÃºmero de viajantes",
    notes: "ObservaÃ§Ãµes da reserva",
    submitBooking: "Solicitar reserva",
  },

  en: {
    langLabel: "Language",
    heroTitle1: "Discover the Paradise",
    heroTitle2: "of MarajÃ³ Island",
    heroSubtitle: "Wherever you want to go, we take you there. Find the best offers for your next adventure.",
    heroButton: "Search",
    tabs: ["Flights", "Hotels", "Packages", "Activities", "Bus", "Cars"],
    stats: ["Hotels", "Destinations", "Travelers", "Rating"],
    heroImageAlt: "Tropical beach in MarajÃ³",
    heroFieldOrigin: "Origin",
    heroFieldDestination: "Destination",
    heroFieldDates: "Dates",
    heroFieldPassengers: "Passengers",

    home: {
      heroKicker: "Destination platform â€¢ MarajÃ³ Island",
      heroSearchAria: "Search by category",
      homeHeroImageAlt: "Landscape of MarajÃ³ Island with beach and open sky",
      destinationsEyebrow: "Exploration",
      featureEyebrow: "Trust",
      featureLocationLabel: "Location",
      featureDurationLabel: "Duration",
      featureInvestmentLabel: "Investment",
      featureGalleryAlt: "MarajÃ³ gallery",
      newsletterEyebrow: "Premium newsletter",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Your email",
      newsletterEmailPlaceholder: "Your best email",
      newsletterImageAlt: "Traveler preparing the next trip",
      offersEyebrow: "Booking",
      offersConditions: "View conditions",
      partnersEyebrow: "Ecosystem",
      partnersBadge: "Partner",
      routesEyebrow: "Comparison",
      routesViewPackage: "View package",
      socialEyebrow: "Social proof",
      socialRatingLabel: "Rating",
      socialQuoteOpen: "â€œ",
      socialQuoteClose: "â€",
      topExperiencesEyebrow: "Exploration",
      topExperiencesDetailsLabel: "View details",
      travelGuideEyebrow: "Planning",
      travelGuideReadTimeSuffix: "read",
      travelGuideReadCta: "Read guide",
      whyEyebrow: "Imagination",
    },

    pages: {
      experiences: {
        eyebrow: "Experiences",
        title: "Curated experiences to live MarajÃ³",
        subtitle: "Premium selection with local support and secure booking. Compare profiles and find the right experience for your moment.",
        detailsCta: "View details",
      },
      experienceDetail: {
        eyebrow: "Details",
        title: "What makes this experience unique",
        includedTitle: "What's included",
        priceLabel: "Investment from",
        perPersonLabel: "Per person â€¢ rating",
        reserveNow: "Book now",
        planWithConcierge: "Plan with concierge",
        reserveExperience: "Book experience",
        talkToConsultant: "Talk to a consultant",
      },
      packages: {
        eyebrow: "Packages",
        title: "Ready-made itineraries for different travel profiles",
        subtitle: "Combine experiences, stays, and local support with smart, flexible itineraries.",
        priceFrom: "From",
        includes: "Includes",
        itinerary: "Base itinerary",
        reserveCta: "Book package",
        consultCta: "Talk to a consultant",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Personalized planning for your trip",
        subtitle: "Count on our local team to craft the ideal itinerary with real support before, during, and after booking.",
        deliverTitle: "What we deliver",
        deliverItems: [
          "Curated experiences aligned with your profile",
          "Suggestions for itineraries, stays, and logistics",
          "Direct negotiation with local partners",
        ],
        responseTitle: "Response time",
        responseText: "Up to 24 hours with human assistance.",
        nextStepLabel: "Next step",
        nextStepTitle: "Talk to our concierge and receive a tailored plan.",
        whatsappCta: "Continue on WhatsApp",
        whatsappFallback: "Configure `NEXT_PUBLIC_WHATSAPP_NUMBER` to enable contact.",
        whatsappMessage: "Hello! I want to plan a premium trip to MarajÃ³. I'd like help with experiences and packages.",
      },
    },

    premiumBadge: "Premium experience in Soure",
    premiumTitle1: "Pesqueiro",
    premiumTitle2: "Beach",
    premiumText: "One of the most desired landscapes in MarajÃ³. Wide sands, sea, local culture and the unique experience of seeing buffalo integrated into the scenery make Pesqueiro a destination with strong visual and emotional appeal.",
    premiumHighlights: ["Iconic beach in Soure", "Buffalo experience", "Beachfront spots", "Unforgettable sunset"],
    premiumCta1: "Book experience",
    premiumCta2: "See premium packages",
    premiumFooter1: "Premium gallery â€¢ Soure â€¢ MarajÃ³ Island",
    premiumFooter2: "Auto play active â€¢ use arrows",

    packagesBadge: "Featured packages",
    packagesTitle: "Travel Packages",
    packagesSubtitle: "Selected experiences for travelers who want to enjoy the best of MarajÃ³ Island.",
    offerBadge: "Premium offer",
    offerDescription: "One of the most iconic experiences in Soure, with MarajÃ³ scenery, strong photographic appeal and an authentic connection to local culture.",
    investmentLabel: "Investment",
    detailsButton: "See details",
    bookNow: "Book now",

    experienceBadge: "Premium experience",
    experienceSectionTitle: "A high visual and emotional value experience",
    experienceGalleryTitle: "Gallery",
    includedLabel: "Included",
    continueBooking: "Continue to booking",
    backToPackages: "See packages",

    checkoutBadge: "Complete reservation",
    fullName: "Full name",
    email: "Email",
    phone: "Phone / WhatsApp",
    experienceDate: "Experience date",
    travelers: "Number of travelers",
    notes: "Booking notes",
    submitBooking: "Request booking",
  },

  fr: {
    langLabel: "Langue",
    heroTitle1: "DÃ©couvrez le Paradis",
    heroTitle2: "de lâ€™Ã®le de MarajÃ³",
    heroSubtitle: "OÃ¹ que vous alliez, nous vous y emmenons. Trouvez les meilleures offres pour votre prochaine aventure.",
    heroButton: "Rechercher",
    tabs: ["Vols", "HÃ´tels", "Forfaits", "ActivitÃ©s", "Bus", "Voitures"],
    stats: ["HÃ´tels", "Destinations", "Voyageurs", "Note"],
    heroImageAlt: "Plage tropicale Ã  MarajÃ³",
    heroFieldOrigin: "Origine",
    heroFieldDestination: "Destination",
    heroFieldDates: "Dates",
    heroFieldPassengers: "Voyageurs",

    home: {
      heroKicker: "Plateforme de destination â€¢ ÃŽle de MarajÃ³",
      heroSearchAria: "Recherche par catÃ©gorie",
      homeHeroImageAlt: "Paysage de lâ€™Ã®le de MarajÃ³ avec plage et ciel ouvert",
      destinationsEyebrow: "Exploration",
      featureEyebrow: "Confiance",
      featureLocationLabel: "Lieu",
      featureDurationLabel: "DurÃ©e",
      featureInvestmentLabel: "Investissement",
      featureGalleryAlt: "Galerie MarajÃ³",
      newsletterEyebrow: "Newsletter premium",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Votre email",
      newsletterEmailPlaceholder: "Votre meilleur email",
      newsletterImageAlt: "Voyageur prÃ©parant le prochain voyage",
      offersEyebrow: "RÃ©servation",
      offersConditions: "Voir les conditions",
      partnersEyebrow: "Ã‰cosystÃ¨me",
      partnersBadge: "Partenaire",
      routesEyebrow: "Comparaison",
      routesViewPackage: "Voir le forfait",
      socialEyebrow: "Preuve sociale",
      socialRatingLabel: "Note",
      socialQuoteOpen: "â€œ",
      socialQuoteClose: "â€",
      topExperiencesEyebrow: "Exploration",
      topExperiencesDetailsLabel: "Voir les dÃ©tails",
      travelGuideEyebrow: "Planification",
      travelGuideReadTimeSuffix: "de lecture",
      travelGuideReadCta: "Lire le guide",
      whyEyebrow: "Imagination",
    },

    pages: {
      experiences: {
        eyebrow: "ExpÃ©riences",
        title: "Des expÃ©riences sÃ©lectionnÃ©es pour vivre MarajÃ³",
        subtitle: "SÃ©lection premium avec support local et rÃ©servation sÃ©curisÃ©e. Comparez les profils et trouvez l'expÃ©rience idÃ©ale.",
        detailsCta: "Voir les dÃ©tails",
      },
      experienceDetail: {
        eyebrow: "DÃ©tails",
        title: "Ce qui rend cette expÃ©rience unique",
        includedTitle: "Ce qui est inclus",
        priceLabel: "Investissement Ã  partir de",
        perPersonLabel: "Par personne â€¢ note",
        reserveNow: "RÃ©server maintenant",
        planWithConcierge: "Planifier avec le concierge",
        reserveExperience: "RÃ©server l'expÃ©rience",
        talkToConsultant: "Parler Ã  un conseiller",
      },
      packages: {
        eyebrow: "Forfaits",
        title: "ItinÃ©raires prÃªts pour diffÃ©rents profils de voyage",
        subtitle: "Combinez expÃ©riences, hÃ©bergements et support local avec des itinÃ©raires flexibles.",
        priceFrom: "Ã€ partir de",
        includes: "Inclus",
        itinerary: "ItinÃ©raire de base",
        reserveCta: "RÃ©server le forfait",
        consultCta: "Parler Ã  un conseiller",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Planification personnalisÃ©e pour votre voyage",
        subtitle: "Comptez sur notre Ã©quipe locale pour construire lâ€™itinÃ©raire idÃ©al, avec un support rÃ©el avant, pendant et aprÃ¨s la rÃ©servation.",
        deliverTitle: "Ce que nous livrons",
        deliverItems: [
          "ExpÃ©riences sÃ©lectionnÃ©es selon votre profil",
          "Suggestions dâ€™itinÃ©raires, dâ€™hÃ©bergements et de logistique",
          "NÃ©gociation directe avec les partenaires locaux",
        ],
        responseTitle: "DÃ©lai de rÃ©ponse",
        responseText: "Jusquâ€™Ã  24 heures avec un accompagnement humain.",
        nextStepLabel: "Prochaine Ã©tape",
        nextStepTitle: "Parlez Ã  notre concierge et recevez un plan sur mesure.",
        whatsappCta: "Continuer sur WhatsApp",
        whatsappFallback: "Configurez `NEXT_PUBLIC_WHATSAPP_NUMBER` pour activer le contact.",
        whatsappMessage: "Bonjour ! Je veux planifier un voyage premium Ã  MarajÃ³. J'aimerais de l'aide pour les expÃ©riences et les forfaits.",
      },
    },

    premiumBadge: "ExpÃ©rience premium Ã  Soure",
    premiumTitle1: "Plage de",
    premiumTitle2: "Pesqueiro",
    premiumText: "Lâ€™un des paysages les plus dÃ©sirÃ©s de MarajÃ³. Sable vaste, mer, culture locale et lâ€™expÃ©rience unique de voir des buffles intÃ©grÃ©s au dÃ©cor font de Pesqueiro une destination Ã  fort impact visuel et Ã©motionnel.",
    premiumHighlights: ["Plage emblÃ©matique de Soure", "ExpÃ©rience avec les buffles", "Espaces en bord de mer", "Coucher de soleil inoubliable"],
    premiumCta1: "RÃ©server lâ€™expÃ©rience",
    premiumCta2: "Voir les forfaits premium",
    premiumFooter1: "Galerie premium â€¢ Soure â€¢ ÃŽle de MarajÃ³",
    premiumFooter2: "Lecture automatique â€¢ utilisez les flÃ¨ches",

    packagesBadge: "Forfaits en vedette",
    packagesTitle: "Forfaits de Voyage",
    packagesSubtitle: "Des expÃ©riences sÃ©lectionnÃ©es pour les voyageurs qui souhaitent vivre le meilleur de lâ€™Ã®le de MarajÃ³.",
    offerBadge: "Offre premium",
    offerDescription: "Lâ€™une des expÃ©riences les plus emblÃ©matiques de Soure, avec un paysage marajoara, un fort attrait photographique et un lien authentique avec la culture locale.",
    investmentLabel: "Investissement",
    detailsButton: "Voir les dÃ©tails",
    bookNow: "RÃ©server maintenant",

    experienceBadge: "ExpÃ©rience premium",
    experienceSectionTitle: "Une expÃ©rience Ã  forte valeur visuelle et Ã©motionnelle",
    experienceGalleryTitle: "Galerie",
    includedLabel: "Inclus",
    continueBooking: "Continuer la rÃ©servation",
    backToPackages: "Voir les forfaits",

    checkoutBadge: "Finaliser la rÃ©servation",
    fullName: "Nom complet",
    email: "Email",
    phone: "TÃ©lÃ©phone / WhatsApp",
    experienceDate: "Date de lâ€™expÃ©rience",
    travelers: "Nombre de voyageurs",
    notes: "Observations de la rÃ©servation",
    submitBooking: "Demander la rÃ©servation",
  },

  es: {
    langLabel: "Idioma",
    heroTitle1: "Descubre el ParaÃ­so",
    heroTitle2: "de la Isla de MarajÃ³",
    heroSubtitle: "A donde quieras ir, nosotros te llevamos. Encuentra las mejores ofertas para tu prÃ³xima aventura.",
    heroButton: "Buscar",
    tabs: ["Vuelos", "Hoteles", "Paquetes", "Actividades", "Bus", "Autos"],
    stats: ["Hoteles", "Destinos", "Viajeros", "CalificaciÃ³n"],
    heroImageAlt: "Playa tropical en MarajÃ³",
    heroFieldOrigin: "Origen",
    heroFieldDestination: "Destino",
    heroFieldDates: "Fechas",
    heroFieldPassengers: "Pasajeros",

    home: {
      heroKicker: "Plataforma de destino â€¢ Isla de MarajÃ³",
      heroSearchAria: "BÃºsqueda por categorÃ­a",
      homeHeroImageAlt: "Paisaje de la Isla de MarajÃ³ con playa y cielo abierto",
      destinationsEyebrow: "ExploraciÃ³n",
      featureEyebrow: "Confianza",
      featureLocationLabel: "UbicaciÃ³n",
      featureDurationLabel: "DuraciÃ³n",
      featureInvestmentLabel: "InversiÃ³n",
      featureGalleryAlt: "GalerÃ­a MarajÃ³",
      newsletterEyebrow: "BoletÃ­n premium",
      newsletterAriaLabel: "BoletÃ­n",
      newsletterEmailLabel: "Tu email",
      newsletterEmailPlaceholder: "Tu mejor email",
      newsletterImageAlt: "Viajero preparando el prÃ³ximo viaje",
      offersEyebrow: "Reserva",
      offersConditions: "Ver condiciones",
      partnersEyebrow: "Ecosistema",
      partnersBadge: "Socio",
      routesEyebrow: "ComparaciÃ³n",
      routesViewPackage: "Ver paquete",
      socialEyebrow: "Prueba social",
      socialRatingLabel: "CalificaciÃ³n",
      socialQuoteOpen: "â€œ",
      socialQuoteClose: "â€",
      topExperiencesEyebrow: "ExploraciÃ³n",
      topExperiencesDetailsLabel: "Ver detalles",
      travelGuideEyebrow: "PlanificaciÃ³n",
      travelGuideReadTimeSuffix: "de lectura",
      travelGuideReadCta: "Leer guÃ­a",
      whyEyebrow: "ImaginaciÃ³n",
    },

    pages: {
      experiences: {
        eyebrow: "Experiencias",
        title: "Experiencias seleccionadas para vivir MarajÃ³",
        subtitle: "SelecciÃ³n premium con soporte local y reserva segura. Compara perfiles y encuentra la experiencia ideal.",
        detailsCta: "Ver detalles",
      },
      experienceDetail: {
        eyebrow: "Detalles",
        title: "QuÃ© hace Ãºnica esta experiencia",
        includedTitle: "QuÃ© estÃ¡ incluido",
        priceLabel: "InversiÃ³n desde",
        perPersonLabel: "Por persona â€¢ calificaciÃ³n",
        reserveNow: "Reservar ahora",
        planWithConcierge: "Planear con concierge",
        reserveExperience: "Reservar experiencia",
        talkToConsultant: "Hablar con un consultor",
      },
      packages: {
        eyebrow: "Paquetes",
        title: "Itinerarios listos para diferentes perfiles de viaje",
        subtitle: "Combina experiencias, hospedajes y soporte local con itinerarios flexibles.",
        priceFrom: "Desde",
        includes: "Incluye",
        itinerary: "Itinerario base",
        reserveCta: "Reservar paquete",
        consultCta: "Hablar con un consultor",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "PlanificaciÃ³n personalizada para tu viaje",
        subtitle: "Cuenta con nuestro equipo local para diseÃ±ar el itinerario ideal, con soporte real antes, durante y despuÃ©s de la reserva.",
        deliverTitle: "Lo que entregamos",
        deliverItems: [
          "Experiencias curadas segÃºn tu perfil",
          "Sugerencias de itinerarios, hospedajes y logÃ­stica",
          "NegociaciÃ³n directa con socios locales",
        ],
        responseTitle: "Tiempo de respuesta",
        responseText: "Hasta 24 horas con atenciÃ³n humana.",
        nextStepLabel: "PrÃ³ximo paso",
        nextStepTitle: "Habla con nuestro concierge y recibe un plan a medida.",
        whatsappCta: "Continuar en WhatsApp",
        whatsappFallback: "Configura `NEXT_PUBLIC_WHATSAPP_NUMBER` para habilitar el contacto.",
        whatsappMessage: "Â¡Hola! Quiero planear un viaje premium a MarajÃ³. Me gustarÃ­a ayuda con experiencias y paquetes.",
      },
    },

    premiumBadge: "Experiencia premium en Soure",
    premiumTitle1: "Playa de",
    premiumTitle2: "Pesqueiro",
    premiumText: "Uno de los paisajes mÃ¡s deseados de MarajÃ³. Arena amplia, mar, cultura local y la experiencia Ãºnica de ver bÃºfalos integrados al entorno hacen de Pesqueiro un destino de gran impacto visual y emocional.",
    premiumHighlights: ["Playa icÃ³nica de Soure", "Experiencia con bÃºfalos", "Espacios frente al mar", "Atardecer inolvidable"],
    premiumCta1: "Reservar experiencia",
    premiumCta2: "Ver paquetes premium",
    premiumFooter1: "GalerÃ­a premium â€¢ Soure â€¢ Isla de MarajÃ³",
    premiumFooter2: "ReproducciÃ³n automÃ¡tica â€¢ usa las flechas",

    packagesBadge: "Paquetes destacados",
    packagesTitle: "Paquetes de Viaje",
    packagesSubtitle: "Experiencias seleccionadas para viajeros que desean vivir lo mejor de la Isla de MarajÃ³.",
    offerBadge: "Oferta premium",
    offerDescription: "Una de las experiencias mÃ¡s emblemÃ¡ticas de Soure, con paisaje marajoara, gran atractivo fotogrÃ¡fico y conexiÃ³n autÃ©ntica con la cultura local.",
    investmentLabel: "InversiÃ³n",
    detailsButton: "Ver detalles",
    bookNow: "Reservar ahora",

    experienceBadge: "Experiencia premium",
    experienceSectionTitle: "Una experiencia de alto valor visual y emocional",
    experienceGalleryTitle: "GalerÃ­a",
    includedLabel: "Incluye",
    continueBooking: "Continuar con la reserva",
    backToPackages: "Ver paquetes",

    checkoutBadge: "Finalizar reserva",
    fullName: "Nombre completo",
    email: "Email",
    phone: "TelÃ©fono / WhatsApp",
    experienceDate: "Fecha de la experiencia",
    travelers: "NÃºmero de viajeros",
    notes: "Observaciones de la reserva",
    submitBooking: "Solicitar reserva",
  },
} as const