export const siteContent = {
  pt: {
    langLabel: "Idioma",
    heroTitle1: "Descubra o Paraíso",
    heroTitle2: "da Ilha de Marajó",
    heroSubtitle: "Aonde quer que você vá, nós te levamos. Encontre as melhores ofertas para sua próxima aventura.",
    heroButton: "Buscar",
    tabs: ["Voos", "Hotéis", "Pacotes", "Atividades", "Ônibus", "Carros"],
    stats: ["Hotéis", "Destinos", "Viajantes", "Avaliação"],
    heroImageAlt: "Praia tropical de Marajó",
    heroFieldOrigin: "Origem",
    heroFieldDestination: "Destino",
    heroFieldDates: "Datas",
    heroFieldPassengers: "Passageiros",

    home: {
      heroKicker: "Plataforma de destino • Ilha de Marajó",
      heroSearchAria: "Busca por categoria",
      homeHeroImageAlt: "Paisagem da Ilha de Marajó com praia e céu amplo",
      destinationsEyebrow: "Exploração",
      featureEyebrow: "Confiança",
      featureLocationLabel: "Local",
      featureDurationLabel: "Duração",
      featureInvestmentLabel: "Investimento",
      featureGalleryAlt: "Galeria Marajó",
      newsletterEyebrow: "Newsletter premium",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Seu email",
      newsletterEmailPlaceholder: "Seu melhor email",
      newsletterImageAlt: "Viajante preparando a próxima viagem",
      offersEyebrow: "Reserva",
      offersConditions: "Ver condições",
      partnersEyebrow: "Ecossistema",
      partnersBadge: "Parceiro",
      routesEyebrow: "Comparação",
      routesViewPackage: "Ver pacote",
      socialEyebrow: "Prova social",
      socialRatingLabel: "Avaliação",
      socialQuoteOpen: "“",
      socialQuoteClose: "”",
      topExperiencesEyebrow: "Exploração",
      topExperiencesDetailsLabel: "Ver detalhes",
      travelGuideEyebrow: "Planejamento",
      travelGuideReadTimeSuffix: "de leitura",
      travelGuideReadCta: "Ler guia",
      whyEyebrow: "Imaginação",
    },

    pages: {
      experiences: {
        eyebrow: "Experiências",
        title: "Experiências curadas para viver o Marajó",
        subtitle: "Seleção premium com suporte local e reserva segura. Compare perfis e encontre a experiência certa para o seu momento.",
        detailsCta: "Ver detalhes",
      },
      experienceDetail: {
        eyebrow: "Detalhes",
        title: "O que torna essa experiência única",
        includedTitle: "O que está incluído",
        priceLabel: "Investimento a partir de",
        perPersonLabel: "Por pessoa • avaliação",
        reserveNow: "Reservar agora",
        planWithConcierge: "Planejar com concierge",
        reserveExperience: "Reservar experiência",
        talkToConsultant: "Falar com consultor",
      },
      packages: {
        eyebrow: "Pacotes",
        title: "Roteiros prontos para diferentes perfis de viagem",
        subtitle: "Combine experiências, hospedagens e suporte local com roteiros inteligentes e flexíveis.",
        priceFrom: "A partir de",
        includes: "Inclui",
        itinerary: "Itinerário base",
        reserveCta: "Reservar pacote",
        consultCta: "Falar com consultor",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Planejamento personalizado para sua viagem",
        subtitle: "Conte com nosso time local para montar o roteiro ideal, com suporte real antes, durante e depois da reserva.",
        deliverTitle: "O que vamos entregar",
        deliverItems: [
          "Curadoria de experiências alinhadas ao seu perfil",
          "Sugestão de roteiros, hospedagens e logística",
          "Negociação direta com parceiros locais",
        ],
        responseTitle: "Tempo de resposta",
        responseText: "Até 24 horas com atendimento humano.",
        nextStepLabel: "Próximo passo",
        nextStepTitle: "Fale com nosso concierge e receba um plano sob medida.",
        whatsappCta: "Continuar no WhatsApp",
        whatsappFallback: "Configure `NEXT_PUBLIC_WHATSAPP_NUMBER` para habilitar o contato.",
        whatsappMessage: "Olá! Quero planejar uma viagem premium para o Marajó. Gostaria de ajuda com experiências e pacotes.",
      },
    },

    premiumBadge: "Experiência premium em Soure",
    premiumTitle1: "Praia do",
    premiumTitle2: "Pesqueiro",
    premiumText: "Um dos cenários mais desejados do Marajó. Areia ampla, mar, cultura local e a experiência única de ver búfalos integrados à paisagem fazem do Pesqueiro um destino de alto apelo visual e emocional.",
    premiumHighlights: ["Praia icônica de Soure", "Experiência com búfalos", "Barracas à beira-mar", "Pôr do sol inesquecível"],
    premiumCta1: "Reservar experiência",
    premiumCta2: "Ver pacotes premium",
    premiumFooter1: "Galeria premium • Soure • Ilha de Marajó",
    premiumFooter2: "Auto play ativo • use as setas",

    packagesBadge: "Pacotes em destaque",
    packagesTitle: "Pacotes de Viagem",
    packagesSubtitle: "Experiências selecionadas para viajantes que desejam viver o melhor da Ilha de Marajó.",
    offerBadge: "Oferta premium",
    offerDescription: "Uma das experiências mais emblemáticas de Soure, com paisagem marajoara, forte apelo fotográfico e conexão autêntica com a cultura local.",
    investmentLabel: "Investimento",
    detailsButton: "Ver detalhes",
    bookNow: "Reservar agora",

    experienceBadge: "Experiência premium",
    experienceSectionTitle: "Uma experiência de alto valor visual e emocional",
    experienceGalleryTitle: "Galeria",
    includedLabel: "Incluído",
    continueBooking: "Continuar para reserva",
    backToPackages: "Ver pacotes",

    checkoutBadge: "Finalizar reserva",
    fullName: "Nome completo",
    email: "Email",
    phone: "Telefone / WhatsApp",
    experienceDate: "Data da experiência",
    travelers: "Número de viajantes",
    notes: "Observações da reserva",
    submitBooking: "Solicitar reserva",
  },

  en: {
    langLabel: "Language",
    heroTitle1: "Discover the Paradise",
    heroTitle2: "of Marajó Island",
    heroSubtitle: "Wherever you want to go, we take you there. Find the best offers for your next adventure.",
    heroButton: "Search",
    tabs: ["Flights", "Hotels", "Packages", "Activities", "Bus", "Cars"],
    stats: ["Hotels", "Destinations", "Travelers", "Rating"],
    heroImageAlt: "Tropical beach in Marajó",
    heroFieldOrigin: "Origin",
    heroFieldDestination: "Destination",
    heroFieldDates: "Dates",
    heroFieldPassengers: "Passengers",

    home: {
      heroKicker: "Destination platform • Marajó Island",
      heroSearchAria: "Search by category",
      homeHeroImageAlt: "Landscape of Marajó Island with beach and open sky",
      destinationsEyebrow: "Exploration",
      featureEyebrow: "Trust",
      featureLocationLabel: "Location",
      featureDurationLabel: "Duration",
      featureInvestmentLabel: "Investment",
      featureGalleryAlt: "Marajó gallery",
      newsletterEyebrow: "Premium newsletter",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Your email",
      newsletterEmailPlaceholder: "Your best email",
      newsletterImageAlt: "Traveler preparing the next trip",
      offersEyebrow: "Booking",
      offersConditions: "View conditions",
      partnersEyebrow: "Ecosystem",
      partnersBadge: "Partner",
      routesEyebrow: "Comparison",
      routesViewPackage: "View package",
      socialEyebrow: "Social proof",
      socialRatingLabel: "Rating",
      socialQuoteOpen: "“",
      socialQuoteClose: "”",
      topExperiencesEyebrow: "Exploration",
      topExperiencesDetailsLabel: "View details",
      travelGuideEyebrow: "Planning",
      travelGuideReadTimeSuffix: "read",
      travelGuideReadCta: "Read guide",
      whyEyebrow: "Imagination",
    },

    pages: {
      experiences: {
        eyebrow: "Experiences",
        title: "Curated experiences to live Marajó",
        subtitle: "Premium selection with local support and secure booking. Compare profiles and find the right experience for your moment.",
        detailsCta: "View details",
      },
      experienceDetail: {
        eyebrow: "Details",
        title: "What makes this experience unique",
        includedTitle: "What's included",
        priceLabel: "Investment from",
        perPersonLabel: "Per person • rating",
        reserveNow: "Book now",
        planWithConcierge: "Plan with concierge",
        reserveExperience: "Book experience",
        talkToConsultant: "Talk to a consultant",
      },
      packages: {
        eyebrow: "Packages",
        title: "Ready-made itineraries for different travel profiles",
        subtitle: "Combine experiences, stays, and local support with smart, flexible itineraries.",
        priceFrom: "From",
        includes: "Includes",
        itinerary: "Base itinerary",
        reserveCta: "Book package",
        consultCta: "Talk to a consultant",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Personalized planning for your trip",
        subtitle: "Count on our local team to craft the ideal itinerary with real support before, during, and after booking.",
        deliverTitle: "What we deliver",
        deliverItems: [
          "Curated experiences aligned with your profile",
          "Suggestions for itineraries, stays, and logistics",
          "Direct negotiation with local partners",
        ],
        responseTitle: "Response time",
        responseText: "Up to 24 hours with human assistance.",
        nextStepLabel: "Next step",
        nextStepTitle: "Talk to our concierge and receive a tailored plan.",
        whatsappCta: "Continue on WhatsApp",
        whatsappFallback: "Configure `NEXT_PUBLIC_WHATSAPP_NUMBER` to enable contact.",
        whatsappMessage: "Hello! I want to plan a premium trip to Marajó. I'd like help with experiences and packages.",
      },
    },

    premiumBadge: "Premium experience in Soure",
    premiumTitle1: "Pesqueiro",
    premiumTitle2: "Beach",
    premiumText: "One of the most desired landscapes in Marajó. Wide sands, sea, local culture and the unique experience of seeing buffalo integrated into the scenery make Pesqueiro a destination with strong visual and emotional appeal.",
    premiumHighlights: ["Iconic beach in Soure", "Buffalo experience", "Beachfront spots", "Unforgettable sunset"],
    premiumCta1: "Book experience",
    premiumCta2: "See premium packages",
    premiumFooter1: "Premium gallery • Soure • Marajó Island",
    premiumFooter2: "Auto play active • use arrows",

    packagesBadge: "Featured packages",
    packagesTitle: "Travel Packages",
    packagesSubtitle: "Selected experiences for travelers who want to enjoy the best of Marajó Island.",
    offerBadge: "Premium offer",
    offerDescription: "One of the most iconic experiences in Soure, with Marajó scenery, strong photographic appeal and an authentic connection to local culture.",
    investmentLabel: "Investment",
    detailsButton: "See details",
    bookNow: "Book now",

    experienceBadge: "Premium experience",
    experienceSectionTitle: "A high visual and emotional value experience",
    experienceGalleryTitle: "Gallery",
    includedLabel: "Included",
    continueBooking: "Continue to booking",
    backToPackages: "See packages",

    checkoutBadge: "Complete reservation",
    fullName: "Full name",
    email: "Email",
    phone: "Phone / WhatsApp",
    experienceDate: "Experience date",
    travelers: "Number of travelers",
    notes: "Booking notes",
    submitBooking: "Request booking",
  },

  fr: {
    langLabel: "Langue",
    heroTitle1: "Découvrez le Paradis",
    heroTitle2: "de lîle de Marajó",
    heroSubtitle: "Où que vous alliez, nous vous y emmenons. Trouvez les meilleures offres pour votre prochaine aventure.",
    heroButton: "Rechercher",
    tabs: ["Vols", "Hôtels", "Forfaits", "Activités", "Bus", "Voitures"],
    stats: ["Hôtels", "Destinations", "Voyageurs", "Note"],
    heroImageAlt: "Plage tropicale à Marajó",
    heroFieldOrigin: "Origine",
    heroFieldDestination: "Destination",
    heroFieldDates: "Dates",
    heroFieldPassengers: "Voyageurs",

    home: {
      heroKicker: "Plateforme de destination • Île de Marajó",
      heroSearchAria: "Recherche par catégorie",
      homeHeroImageAlt: "Paysage de lîle de Marajó avec plage et ciel ouvert",
      destinationsEyebrow: "Exploration",
      featureEyebrow: "Confiance",
      featureLocationLabel: "Lieu",
      featureDurationLabel: "Durée",
      featureInvestmentLabel: "Investissement",
      featureGalleryAlt: "Galerie Marajó",
      newsletterEyebrow: "Newsletter premium",
      newsletterAriaLabel: "Newsletter",
      newsletterEmailLabel: "Votre email",
      newsletterEmailPlaceholder: "Votre meilleur email",
      newsletterImageAlt: "Voyageur préparant le prochain voyage",
      offersEyebrow: "Réservation",
      offersConditions: "Voir les conditions",
      partnersEyebrow: "cosystème",
      partnersBadge: "Partenaire",
      routesEyebrow: "Comparaison",
      routesViewPackage: "Voir le forfait",
      socialEyebrow: "Preuve sociale",
      socialRatingLabel: "Note",
      socialQuoteOpen: "“",
      socialQuoteClose: "”",
      topExperiencesEyebrow: "Exploration",
      topExperiencesDetailsLabel: "Voir les détails",
      travelGuideEyebrow: "Planification",
      travelGuideReadTimeSuffix: "de lecture",
      travelGuideReadCta: "Lire le guide",
      whyEyebrow: "Imagination",
    },

    pages: {
      experiences: {
        eyebrow: "Expériences",
        title: "Des expériences sélectionnées pour vivre Marajó",
        subtitle: "Sélection premium avec support local et réservation sécurisée. Comparez les profils et trouvez l'expérience idéale.",
        detailsCta: "Voir les détails",
      },
      experienceDetail: {
        eyebrow: "Détails",
        title: "Ce qui rend cette expérience unique",
        includedTitle: "Ce qui est inclus",
        priceLabel: "Investissement à partir de",
        perPersonLabel: "Par personne • note",
        reserveNow: "Réserver maintenant",
        planWithConcierge: "Planifier avec le concierge",
        reserveExperience: "Réserver l'expérience",
        talkToConsultant: "Parler à un conseiller",
      },
      packages: {
        eyebrow: "Forfaits",
        title: "Itinéraires prêts pour différents profils de voyage",
        subtitle: "Combinez expériences, hébergements et support local avec des itinéraires flexibles.",
        priceFrom: " partir de",
        includes: "Inclus",
        itinerary: "Itinéraire de base",
        reserveCta: "Réserver le forfait",
        consultCta: "Parler à un conseiller",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Planification personnalisée pour votre voyage",
        subtitle: "Comptez sur notre équipe locale pour construire litinéraire idéal, avec un support réel avant, pendant et après la réservation.",
        deliverTitle: "Ce que nous livrons",
        deliverItems: [
          "Expériences sélectionnées selon votre profil",
          "Suggestions ditinéraires, dhébergements et de logistique",
          "Négociation directe avec les partenaires locaux",
        ],
        responseTitle: "Délai de réponse",
        responseText: "Jusquà 24 heures avec un accompagnement humain.",
        nextStepLabel: "Prochaine étape",
        nextStepTitle: "Parlez à notre concierge et recevez un plan sur mesure.",
        whatsappCta: "Continuer sur WhatsApp",
        whatsappFallback: "Configurez `NEXT_PUBLIC_WHATSAPP_NUMBER` pour activer le contact.",
        whatsappMessage: "Bonjour ! Je veux planifier un voyage premium à Marajó. J'aimerais de l'aide pour les expériences et les forfaits.",
      },
    },

    premiumBadge: "Expérience premium à Soure",
    premiumTitle1: "Plage de",
    premiumTitle2: "Pesqueiro",
    premiumText: "Lun des paysages les plus désirés de Marajó. Sable vaste, mer, culture locale et lexpérience unique de voir des buffles intégrés au décor font de Pesqueiro une destination à fort impact visuel et émotionnel.",
    premiumHighlights: ["Plage emblématique de Soure", "Expérience avec les buffles", "Espaces en bord de mer", "Coucher de soleil inoubliable"],
    premiumCta1: "Réserver lexpérience",
    premiumCta2: "Voir les forfaits premium",
    premiumFooter1: "Galerie premium • Soure • Île de Marajó",
    premiumFooter2: "Lecture automatique • utilisez les flèches",

    packagesBadge: "Forfaits en vedette",
    packagesTitle: "Forfaits de Voyage",
    packagesSubtitle: "Des expériences sélectionnées pour les voyageurs qui souhaitent vivre le meilleur de lîle de Marajó.",
    offerBadge: "Offre premium",
    offerDescription: "Lune des expériences les plus emblématiques de Soure, avec un paysage marajoara, un fort attrait photographique et un lien authentique avec la culture locale.",
    investmentLabel: "Investissement",
    detailsButton: "Voir les détails",
    bookNow: "Réserver maintenant",

    experienceBadge: "Expérience premium",
    experienceSectionTitle: "Une expérience à forte valeur visuelle et émotionnelle",
    experienceGalleryTitle: "Galerie",
    includedLabel: "Inclus",
    continueBooking: "Continuer la réservation",
    backToPackages: "Voir les forfaits",

    checkoutBadge: "Finaliser la réservation",
    fullName: "Nom complet",
    email: "Email",
    phone: "Téléphone / WhatsApp",
    experienceDate: "Date de lexpérience",
    travelers: "Nombre de voyageurs",
    notes: "Observations de la réservation",
    submitBooking: "Demander la réservation",
  },

  es: {
    langLabel: "Idioma",
    heroTitle1: "Descubre el Paraíso",
    heroTitle2: "de la Isla de Marajó",
    heroSubtitle: "A donde quieras ir, nosotros te llevamos. Encuentra las mejores ofertas para tu próxima aventura.",
    heroButton: "Buscar",
    tabs: ["Vuelos", "Hoteles", "Paquetes", "Actividades", "Bus", "Autos"],
    stats: ["Hoteles", "Destinos", "Viajeros", "Calificación"],
    heroImageAlt: "Playa tropical en Marajó",
    heroFieldOrigin: "Origen",
    heroFieldDestination: "Destino",
    heroFieldDates: "Fechas",
    heroFieldPassengers: "Pasajeros",

    home: {
      heroKicker: "Plataforma de destino • Isla de Marajó",
      heroSearchAria: "Búsqueda por categoría",
      homeHeroImageAlt: "Paisaje de la Isla de Marajó con playa y cielo abierto",
      destinationsEyebrow: "Exploración",
      featureEyebrow: "Confianza",
      featureLocationLabel: "Ubicación",
      featureDurationLabel: "Duración",
      featureInvestmentLabel: "Inversión",
      featureGalleryAlt: "Galería Marajó",
      newsletterEyebrow: "Boletín premium",
      newsletterAriaLabel: "Boletín",
      newsletterEmailLabel: "Tu email",
      newsletterEmailPlaceholder: "Tu mejor email",
      newsletterImageAlt: "Viajero preparando el próximo viaje",
      offersEyebrow: "Reserva",
      offersConditions: "Ver condiciones",
      partnersEyebrow: "Ecosistema",
      partnersBadge: "Socio",
      routesEyebrow: "Comparación",
      routesViewPackage: "Ver paquete",
      socialEyebrow: "Prueba social",
      socialRatingLabel: "Calificación",
      socialQuoteOpen: "“",
      socialQuoteClose: "”",
      topExperiencesEyebrow: "Exploración",
      topExperiencesDetailsLabel: "Ver detalles",
      travelGuideEyebrow: "Planificación",
      travelGuideReadTimeSuffix: "de lectura",
      travelGuideReadCta: "Leer guía",
      whyEyebrow: "Imaginación",
    },

    pages: {
      experiences: {
        eyebrow: "Experiencias",
        title: "Experiencias seleccionadas para vivir Marajó",
        subtitle: "Selección premium con soporte local y reserva segura. Compara perfiles y encuentra la experiencia ideal.",
        detailsCta: "Ver detalles",
      },
      experienceDetail: {
        eyebrow: "Detalles",
        title: "Qué hace única esta experiencia",
        includedTitle: "Qué está incluido",
        priceLabel: "Inversión desde",
        perPersonLabel: "Por persona • calificación",
        reserveNow: "Reservar ahora",
        planWithConcierge: "Planear con concierge",
        reserveExperience: "Reservar experiencia",
        talkToConsultant: "Hablar con un consultor",
      },
      packages: {
        eyebrow: "Paquetes",
        title: "Itinerarios listos para diferentes perfiles de viaje",
        subtitle: "Combina experiencias, hospedajes y soporte local con itinerarios flexibles.",
        priceFrom: "Desde",
        includes: "Incluye",
        itinerary: "Itinerario base",
        reserveCta: "Reservar paquete",
        consultCta: "Hablar con un consultor",
      },
      planTrip: {
        eyebrow: "Concierge",
        title: "Planificación personalizada para tu viaje",
        subtitle: "Cuenta con nuestro equipo local para diseñar el itinerario ideal, con soporte real antes, durante y después de la reserva.",
        deliverTitle: "Lo que entregamos",
        deliverItems: [
          "Experiencias curadas según tu perfil",
          "Sugerencias de itinerarios, hospedajes y logística",
          "Negociación directa con socios locales",
        ],
        responseTitle: "Tiempo de respuesta",
        responseText: "Hasta 24 horas con atención humana.",
        nextStepLabel: "Próximo paso",
        nextStepTitle: "Habla con nuestro concierge y recibe un plan a medida.",
        whatsappCta: "Continuar en WhatsApp",
        whatsappFallback: "Configura `NEXT_PUBLIC_WHATSAPP_NUMBER` para habilitar el contacto.",
        whatsappMessage: "¡Hola! Quiero planear un viaje premium a Marajó. Me gustaría ayuda con experiencias y paquetes.",
      },
    },

    premiumBadge: "Experiencia premium en Soure",
    premiumTitle1: "Playa de",
    premiumTitle2: "Pesqueiro",
    premiumText: "Uno de los paisajes más deseados de Marajó. Arena amplia, mar, cultura local y la experiencia única de ver búfalos integrados al entorno hacen de Pesqueiro un destino de gran impacto visual y emocional.",
    premiumHighlights: ["Playa icónica de Soure", "Experiencia con búfalos", "Espacios frente al mar", "Atardecer inolvidable"],
    premiumCta1: "Reservar experiencia",
    premiumCta2: "Ver paquetes premium",
    premiumFooter1: "Galería premium • Soure • Isla de Marajó",
    premiumFooter2: "Reproducción automática • usa las flechas",

    packagesBadge: "Paquetes destacados",
    packagesTitle: "Paquetes de Viaje",
    packagesSubtitle: "Experiencias seleccionadas para viajeros que desean vivir lo mejor de la Isla de Marajó.",
    offerBadge: "Oferta premium",
    offerDescription: "Una de las experiencias más emblemáticas de Soure, con paisaje marajoara, gran atractivo fotográfico y conexión auténtica con la cultura local.",
    investmentLabel: "Inversión",
    detailsButton: "Ver detalles",
    bookNow: "Reservar ahora",

    experienceBadge: "Experiencia premium",
    experienceSectionTitle: "Una experiencia de alto valor visual y emocional",
    experienceGalleryTitle: "Galería",
    includedLabel: "Incluye",
    continueBooking: "Continuar con la reserva",
    backToPackages: "Ver paquetes",

    checkoutBadge: "Finalizar reserva",
    fullName: "Nombre completo",
    email: "Email",
    phone: "Teléfono / WhatsApp",
    experienceDate: "Fecha de la experiencia",
    travelers: "Número de viajeros",
    notes: "Observaciones de la reserva",
    submitBooking: "Solicitar reserva",
  },
} as const
